#! /bin/bash
cat js/ICanHaz.js/ICanHaz.js \
    js/audiolet/Audiolet.js \
    js/Main.js \
    js/Playlist.js \
    js/Track.js \
    js/PlaylistView.js \
    js/TrackView.js \
    js/UID.js \
    js/Player.js \
> js/compiled/SlowCloud.js
